tradeofexile/Models/LeagueSelectorViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using tradeofexile.models.EntityItems;

namespace tradeofexile.models
{
    public class LeagueSelectorViewModel
    {
        public SelectListItem SelectedLeague { get; set; }
        public List<SelectListItem> LeagueSelectList { get; set; }
        public LeagueSelectorViewModel()
        {
            LeagueSelectList = PopulateLeagueSelectList();
        }
        private List<SelectListItem> PopulateLeagueSelectList()
        {
            List<SelectListItem> list = new List<SelectListItem>();
            foreach (var x in Enum.GetValues(typeof(LeagueType)))
            {
                if (x.ToString() != "Other")
                {
                    var selectLi = new SelectListItem();
                    selectLi.Text = x.ToString();
                    selectLi.Value = ((int)x).ToString();
                    list.Add(selectLi);
                }
                
            }
            return list;
        }

    }
}

tradeofexile/Controllers/ArmourController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using tradeofexile.application.Interfaces;
using tradeofexile.application.Queries.GetUniques;
using tradeofexile.application.Utilities;
using tradeofexile.models.EntityItems;
using tradeofexile.Models;

namespace tradeofexile.Controllers
{
    public class ArmourController : Controller
    {
        private readonly IMediator _mediator;
        public ArmourController(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            int selectedLeague;
            int.TryParse(HttpContext.Request.Cookies["selectedLeagueId"], out selectedLeague);
            var armourVM = new ItemsViewModel();
            armourVM.PagingInfo = new PagingInfo() { CurrentPage = page, ItemsPerPage = 5 };
            armourVM.ItemsToShow = await _mediator.Send(new GetUniquesQuery((LeagueType)selectedLeague, ItemCategory.Armour, nameof(CacheKeys.Armour)));
            return View(armourVM);
        }
    }
}

tradeofexile/Controllers/FlasksController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using tradeofexile.application.Queries.GetUniques;
using tradeofexile.application.Utilities;
using tradeofexile.models.EntityItems;
using tradeofexile.Models;

namespace tradeofexile.Controllers
{
    public class FlasksController : Controller
    {
        private readonly IMediator _mediator;
        public FlasksController(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            int selectedLeague;
            int.TryParse(HttpContext.Request.Cookies["selectedLeagueId"], out selectedLeague);
            var flasksVM = new ItemsViewModel();
            flasksVM.PagingInfo = new PagingInfo() { CurrentPage = page, ItemsPerPage = 5 };
            flasksVM.ItemsToShow = await _mediator.Send(new GetUniquesQuery((LeagueType)selectedLeague, ItemCategory.Flasks, nameof(CacheKeys.Flasks)));
            return View(flasksVM);
        }
    }
}

tradeofexile/Controllers/JewelController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using tradeofexile.application.Queries.GetUniques;
using tradeofexile.application.Utilities;
using tradeofexile.models.EntityItems;
using tradeofexile.Models;

namespace tradeofexile.Controllers
{
    public class JewelController : Controller
    {
        private readonly IMediator _mediator;
        public JewelController(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            int selectedLeague;
            int.TryParse(HttpContext.Request.Cookies["selectedLeagueId"], out selectedLeague);
            var jewelVM = new ItemsViewModel();
            jewelVM.PagingInfo = new PagingInfo() { CurrentPage = page, ItemsPerPage = 5 };
            jewelVM.ItemsToShow = await _mediator.Send(new GetUniquesQuery((LeagueType)selectedLeague, ItemCategory.Jewels, nameof(CacheKeys.Jewels)));
            return View(jewelVM);
        }
    }
}

tradeofexile/Controllers/MapsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using tradeofexile.application.Utilities;
using tradeofexile.models.EntityItems;
using tradeofexile.Models;
using MediatR;
using tradeofexile.application.Queries.GetUniques;
using System.Threading.Tasks;

namespace tradeofexile.Controllers
{
    public class MapsController : Controller
    {
        private readonly IMediator _mediator;
        public MapsController(IMediator mediator)
        {
            _mediator = mediator;
        }
        public async Task<IActionResult> Index(int page = 1)
        {
            int selectedLeague;
            int.TryParse(HttpContext.Request.Cookies["selectedLeagueId"], out selectedLeague);
            var mapsVM = new ItemsViewModel();
            mapsVM.PagingInfo = new PagingInfo() { CurrentPage = page, ItemsPerPage = 5 };
            mapsVM.ItemsToShow = await _mediator.Send(new GetUniquesQuery((LeagueType)selectedLeague, ItemCategory.Maps, nameof(CacheKeys.Maps)));
            return View(mapsVM);
        }
    }
}

tradeofexile/Views/Shared/_ItemOverview.cshtml
<body onload="enhance7DaysChangePresentation()">
    <table class="item-overview">
        <thead class="">
            <tr>
                <th>

                </th>
                <th class="th-name">
                    Name
                </th>
                <th>
                </th>
                <th class="th-value">
                    Value
                </th>
                <th class="th-seven-days-change">
                    7 days change
                </th>
                <th class="th-occurances">
                    Occurances
                </th>
            </tr>
        </thead>
        <tbody class="item-overview-tbody">
            @foreach (var item in Model.ItemsToShow)
            {
                <tr class="item-tr">
                    <td class="item-icon"><img class="item-img" src="@item.IconLink." /></td>
                    <td class="item-name">@item.Name</td>
                    <td class="item-price-ammount">@item.Price.Ammount</td>
                    <td class="item-price-type"><img class="price-img" src="@item.Price.IconLink" /></td>
                    <td class="item-seven-days-change">@item.SevenDaysChange</td>
                    <td class="item-occurances">@item.Occurances</td>
                </tr>
            }
        </tbody>
    </table>


</body>

<script>
    function enhance7DaysChangePresentation() {
        var changes = document.getElementsByClassName("item-seven-days-change");
        for (var i = 0; i < changes.length; i++) {
            if (changes[i].innerHTML == 0) {
                changes[i].innerHTML = "no data";
            }
            if (changes[i].innerHTML > 0) {
                changes[i].innerHTML = "+" + changes[i].innerHTML + "%";
                changes[i].style.color = "#42f587";
            }
            if (changes[i].innerHTML < 0) {
                changes[i].innerHTML += "%";
                changes[i].style.color = "#f2685e";
            }
        }
    }
</script>

tradeofexile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tradeofexile</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">tradeofexile</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Starcraft">Starcraft</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Weapons" asp-action="Index">DAWAJ</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@





   <div class="main-container">
        <div class="top-bar">
            <partial name="_TopBar" />
        </div>
        <div class="main">
            <div class="left-menu">
                <partial name="_LeftMenu" />
            </div>
            <div class="content-container">
                <div class="content">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

tradeofexile/Views/Shared/_LeagueSelector.cshtml
@model LeagueSelectorViewModel
@{
}

@using (Html.BeginForm("ChangeSelectedLeague", "Home", FormMethod.Post, new { @class="league-selector-form"}))
{
    @Html.DropDownListFor(
    x => x.SelectedLeague,
    Model.LeagueSelectList.Where(x=>x.Value!=Context.Request.Cookies["selectedLeagueId"]).ToList(),
    Context.Request.Cookies["selectedLeagueText"].ToString() ,
    new { @class="league-selector", onChange = "this.form.submit()" })
}

 

tradeofexile/Views/Shared/_LeftMenu.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<nav id="sideBar">
    <ul class="categories-list">
        <li>
            <a class="category-link" asp-controller="Weapons" asp-action="Index">
                <img class="category-img" src="https://web.poecdn.com/image/Art/2DItems/Weapons/OneHandWeapons/OneHandAxes/SoultakerAlt.png?v=91b3bb849dc06bf0600128137d2a47f4&w=2&h=3&scale=1">
                <div class="category-text">Unique Weapons</div>
            </a>
        </li>
        <li>
            <a class="category-link "asp-controller="Armour" asp-action="Index">
                <img class="category-img" src="https://web.poecdn.com/image/Art/2DItems/Armours/BodyArmours/Loreweave.png?v=8b8e4805a3e2c577874bf327ad358aae&w=2&h=3&scale=1">
                <div class="category-text">Unique Armour</div>
            </a>
        </li>
        <li>
            <a class="category-link " asp-controller="DeliriumOrbs" asp-action="Index">
                <img class="category-img" src="https://web.poecdn.com/image/Art/2DItems/Currency/Delirium/DeliriumOrbProphecies.png?v=75c8f403d6e88a78c911abff7c82ea65&w=1&h=1&scale=1">
                <div class="category-text">Delirium Orbs</div>
            </a>
        </li>
        <li>
            <a class="category-link" asp-controller="Currencies" asp-action="Index">
                <img class="category-img" src="https://web.poecdn.com/image/Art/2DItems/Currency/CurrencyRerollRare.png?v=c60aa876dd6bab31174df91b1da1b4f9&w=1&h=1&scale=1">
                <div class="category-text">Currency</div>
            </a>
        </li>
        <li>
            <a class="category-link " asp-controller="Jewel" asp-action="Index">
                <img class="category-img" src="https://web.poecdn.com/image/Art/2DItems/Jewels/EternalEmpireCivilization.png?v=d0ba60d78abe5d980947d801df1c0f7b&w=1&h=1&scale=1">
                <div class="category-text">Unique Jewels</div>
            </a>
        </li>
        <li>
            <a class="category-link " asp-controller="Flasks" asp-action="Index">
                <img class="category-img" src="https://web.poecdn.com/gen/image/WzksMTQseyJmIjoiMkRJdGVtc1wvRmxhc2tzXC9QaGFudG9tQmxvb2QiLCJ3IjoxLCJoIjoyLCJzY2FsZSI6dHJ1ZSwibGV2ZWwiOjF9XQ/0d2070b13a/Item.png">
                <div class="category-text">Unique Flasks </div>
            </a>
        </li>
        <li>
            <a class="category-link " asp-controller="Maps" asp-action="Index">
                <img class="category-img" src="https://web.poecdn.com/image/Art/2DItems/Maps/LabyrinthHarvest.png?v=5d78da2b494eff07ff426c5299fec8ce&w=1&h=1&scale=1">
                <div class="category-text">Unique Maps</div>
            </a>
        </li>
    </ul>
</nav>

tradeofexile/Views/Shared/_TopBar.cshtml
<div class="item-searchbox-container">
    <input type="search" class="item-searchbox" placeholder="Search item by name">
</div>



<div class="league-selector-container">


    <div class="league-selector-description">
        League:
    </div>

    <partial name="_LeagueSelector" model="new LeagueSelectorViewModel()" />
</div>